# example netlify.toml
[build]
  command = "make build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  GO111MODULE = "on"

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false


[[headers]] 
  for = "/users/*"
  [headers.values]
    Content-Type = "application/activity+json"

[[headers]] 
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type = "application/jrd+json"
    Access-Control-Allow-Origin = "*"

[[redirects]] 
  from = "/api/*" # simplify all calls to serverless functions
  to = "/.netlify/functions/:splat" # all function calls will go to this path
  status = 200 # ok code
  force = true # ensure to always redirect

[[redirects]] 
  from = "/.well-known/webfinger"
  to = "/webfinger.json"
  status = 400
  force = true
  query = {resource = ""}

[[redirects]] 
  from = "/.well-known/webfinger"
  to = "/webfinger.json"
  status = 200
  force = true
  query = {resource = "acct:shrmpy@mastodon.dangersource.net"}

[[redirects]] 
  from = "/.well-known/webfinger"
  to = "/webfinger.json"
  status = 200
  force = true
  query = {resource = "mailto:shrmpy@mastodon.dangersource.net"}

[[redirects]] 
  from = "/.well-known/webfinger"
  to = "/webfinger.json"
  status = 200
  force = true
  query = {resource = "https://mastodon.dangersource.net"}

[[redirects]] 
  from = "/.well-known/webfinger"
  to = "/webfinger.json"
  status = 200
  force = true
  query = {resource = "https://mastodon.dangersource.net/"}

[[redirects]] 
  from = "/users/shrmpy/following"
  to = "/following.json"
  status = 200
  force = true

[[redirects]] 
  from = "/users/shrmpy/followers"
  to = "/followers.json"
  status = 200
  force = true

[[redirects]] 
  from = "/users/shrmpy/featured"
  to = "/featured.json"
  status = 200
  force = true

[[redirects]] 
  from = "/users/shrmpy/toots"
  to = "/toots.json"
  status = 200
  force = true

[[redirects]] 
  from = "/shrmpy/posts"
  to = "/posts"
  status = 200
  force = true

[[redirects]] 
  from = "/users/shrmpy"
  to = "/actor.json"
  status = 200
  force = true

[[redirects]] 
  from = "/@shrmpy"
  to = "/actor.json"
  status = 200
  force = true



