# quick deploy
[template]
[template.environment]
  SELF_ACTOR = "username for this *static* instance"
  DISCORD_WEBHOOK = ""
  GITHUB_AVATAR = ""


# astro+golang build
[build]
  command = "make build"
  functions = "netlify/functions"
  publish = "dist"

[build.environment]
  GO111MODULE = "on"

[[plugins]] 
  package = "netlify-plugin-cypress"

  [plugins.inputs.postBuild]
    enable = true
  
  [plugin.inputs]
    enable = false


[[headers]] 
  for = "/u/*"
  [headers.values]
    Content-Type = "application/activity+json"

[[headers]] 
  for = "/.well-known/webfinger"
  [headers.values]
    Content-Type = "application/jrd+json"
    Access-Control-Allow-Origin = "*"

